"""Feature-owned durable task storage boundary."""
from typing import Protocol, Any

class TaskStore(Protocol):
    def write_task(self, task: dict, *, user_id: str, workspace_id: str, session_id: str | None) -> None: ...
    def claim_task(self, *, user_id: str, workspace_id: str, session_id: str | None) -> dict | None: ...
    def replace_tasks(self, tasks: list[dict], **scope) -> None: ...
    def list_tasks(self, **scope) -> list[dict]: ...
    def append_event(self, event_type: str, payload: Any, **scope) -> str: ...
