"""Workspace-bound tool operations required by the executor."""
from typing import Protocol, Callable
from .models import CommandResult

class ToolPort(Protocol):
    AVAILABLE_TOOLS: dict[str, Callable[[str], str]]
    def run_command(self, args: str) -> CommandResult: ...
    def set_workspace_root(self, root: str) -> None: ...
    def set_project_graph(self, graph) -> None: ...
    def set_github_cli(self, github) -> None: ...
