"""Repository operations consumed by LearningStore."""
from __future__ import annotations
from typing import Protocol, Any

class LearningStore(Protocol):
    def add_proposal_evidence(self, proposal_id: str, evidence_id: str):
        ...
    def append_event(self, event_type: str, payload: Any, *, user_id: str='local', workspace_id: str='default', session_id: str | None=None, task_id: str | None=None):
        ...
    def create_proposal(self, kind: str, content: str, *, confidence: float=0.0, evidence: list[str] | None=None, workspace_id: str='default', user_id: str='local'):
        ...
    def get_learning_runtime(self, *, user_id: str='local', workspace_id: str='default'):
        ...
    def list_events(self, event_type: str | None=None, *, limit: int=100, workspace_id: str='default', session_id: str | None=None, user_id: str | None=None):
        ...
    def list_learning_feature_flags(self, *, user_id: str='local', workspace_id: str='default'):
        ...
    def list_memories(self, *, kind: str | None=None, status: str | None='active', limit: int=100, workspace_id: str='default', session_id: str | None=None, user_id: str | None=None):
        ...
    def list_proposals(self, *, status: str | None=None, workspace_id: str='default', limit: int=100, user_id: str | None=None):
        ...
    def set_learning_runtime(self, mode: str, status: str, *, model: str='', detail: str='', user_id: str='local', workspace_id: str='default'):
        ...
    def update_proposal(self, proposal_id: str, *, status: str, validation: dict[str, Any] | None=None, confidence: float | None=None, workspace_id: str | None=None, user_id: str | None=None):
        ...
