"""Storage and optional semantic indexing boundaries owned by memory."""
from typing import Protocol, Any
from pathlib import Path

class VectorCollection(Protocol):
    def upsert(self, *, ids, documents, metadatas): ...
    def query(self, *, query_texts, n_results, where, include): ...
    def get(self, *, include): ...
    def count(self) -> int: ...
    def delete(self, *, ids): ...

class VectorIndex(Protocol):
    memories: VectorCollection
    files: VectorCollection

class MemoryStore(Protocol):
    path: Path
    def add_proposal_evidence(self, proposal_id: str, evidence_id: str):
        ...
    def append_event(self, event_type: str, payload: Any, *, user_id: str='local', workspace_id: str='default', session_id: str | None=None, task_id: str | None=None):
        ...
    def create_proposal(self, kind: str, content: str, *, confidence: float=0.0, evidence: list[str] | None=None, workspace_id: str='default', user_id: str='local'):
        ...
    def delete_memories(self, ids: list[str], *, workspace_id: str='default', user_id: str | None=None):
        ...
    def list_events(self, event_type: str | None=None, *, limit: int=100, workspace_id: str='default', session_id: str | None=None, user_id: str | None=None):
        ...
    def list_memories(self, *, kind: str | None=None, status: str | None='active', limit: int=100, workspace_id: str='default', session_id: str | None=None, user_id: str | None=None):
        ...
    def list_proposals(self, *, status: str | None=None, workspace_id: str='default', limit: int=100, user_id: str | None=None):
        ...
    def remove_stale_files(self, valid_paths: set[str], *, workspace_id: str='default', user_id: str | None=None):
        ...
    def set_memory_status(self, memory_id: str, status: str, *, workspace_id: str='default', user_id: str | None=None):
        ...
    def update_proposal(self, proposal_id: str, *, status: str, validation: dict[str, Any] | None=None, confidence: float | None=None, workspace_id: str | None=None, user_id: str | None=None):
        ...
    def upsert_file(self, rel_path: str, content: str, *, user_id: str='local', workspace_id: str='default'):
        ...
    def upsert_memory(self, content: str, *, kind: str='episodic', status: str='active', confidence: float=0.5, user_id: str='local', workspace_id: str='default', session_id: str | None=None, source_event_ids: list[str] | None=None, metadata: dict[str, Any] | None=None):
        ...
