#!/usr/bin/env python3
"""Generate the documentation inventory from the live OpenKyrozen surfaces."""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _load_runtime() -> tuple[dict[str, Any], Any, Any]:
    import main
    import server
    from tools import tool_capability

    return main.AVAILABLE_TOOLS, server, tool_capability


def runtime_routes(server: Any) -> list[tuple[str, str]]:
    """Return the documented HTTP routes registered by the FastAPI app."""
    rows: set[tuple[str, str]] = set()
    for route in server.app.routes:
        if route.path != "/" and not route.path.startswith("/api/") and route.path != "/mcp":
            continue
        for method in (route.methods or set()) - {"HEAD", "OPTIONS"}:
            rows.add((method, route.path))
    return sorted(rows, key=lambda row: (row[1], row[0]))


def _first_doc_line(function: Any) -> str:
    doc = inspect.getdoc(function) or "No description provided."
    return doc.splitlines()[0].strip()


def _escape_table(value: str) -> str:
    return re.sub(r"\s+", " ", value.replace("|", "\\|"))


def _mcp_contract(server: Any, name: str, function: Any) -> str:
    schema = server._mcp_tool_schema(name, function)
    properties = schema.get("properties", {})
    if not properties:
        return "none"
    fields = ", ".join(f"`{key}`: {value.get('type', 'value')}" for key, value in properties.items())
    required = schema.get("required", [])
    if required:
        fields += f"; required: {', '.join(f'`{key}`' for key in required)}"
    return fields


def render_inventory() -> str:
    tools, server, tool_capability = _load_runtime()
    git_count = sum(name.startswith("git_") for name in tools)
    routes = runtime_routes(server)
    lines = [
        "<!-- Generated by scripts/generate_tool_inventory.py; do not edit manually. -->",
        "# OpenKyrozen runtime inventory",
        "",
        "This file is generated from the live runtime registry (`main.AVAILABLE_TOOLS`),",
        "the FastAPI route table (`server.app.routes`), and the MCP schema builder.",
        "Run `make docs-check` after changing a tool, endpoint, or MCP contract.",
        "",
        "## Runtime tools",
        "",
        f"- Built-in runtime tools: **{len(tools)}**",
        f"- Names with the `git_` prefix: **{git_count}**",
        "- The CLI Action contract is a plain string in the `args` field.",
        "- Web and MCP exposure is filtered by the configured capability profile.",
        "",
        "| Tool | Capability | Plain-string Action contract | MCP object input schema |",
        "|---|---|---|---|",
    ]
    for name in sorted(tools):
        function = tools[name]
        lines.append(
            f"| `{name}` | `{tool_capability(name)}` | {_escape_table(_first_doc_line(function))} "
            f"| {_escape_table(_mcp_contract(server, name, function))} |"
        )

    lines.extend([
        "",
        "## HTTP and MCP endpoints",
        "",
        "The following paths are registered by the running FastAPI application.",
        "Parameterized names are part of the contract; clients may substitute a value for each brace-delimited parameter.",
        "",
        "| Method | Path |",
        "|---|---|",
    ])
    for method, path in routes:
        lines.append(f"| `{method}` | `{path}` |")

    lines.extend([
        "",
        "## Compatibility contract",
        "",
        "- JSON Action blocks use `{" + '"action": "<tool>", "args": "<plain string>"' + "}`.",
        "- MCP `tools/list` and `server/discover` expose an `inputSchema` for every allowed tool.",
        "- MCP object arguments are explicitly converted to the same plain-string contract; generic tools accept `{" + '"args": "<plain string>"' + "}`.",
        "- Unknown or capability-denied MCP tools are JSON-RPC protocol errors; a tool that runs and returns an error uses `result.isError: true`.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write docs/tool-inventory.md")
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()
    if args.write and args.check:
        parser.error("choose --write or --check")

    target = ROOT / "docs" / "tool-inventory.md"
    rendered = render_inventory()
    if args.write:
        target.write_text(rendered, encoding="utf-8")
        print(f"wrote {target}")
        return 0
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != rendered:
            print("docs/tool-inventory.md is stale; run scripts/generate_tool_inventory.py --write", file=sys.stderr)
            return 1
        tools, server, _ = _load_runtime()
        print(f"runtime inventory is current ({len(tools)} tools, {len(runtime_routes(server))} endpoints)")
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
